config_from_cf:
  cf_deployment_name: (( name ))
  first_app_domain: (( properties.app_domains.[0] ))
  skip_ssl_validation: (( properties.ssl.skip_cert_verify ))
  cc:
    api_uri: (( properties.cc.srv_api_uri ))
  consul:
    log_level: (( properties.consul.agent.log_level ))
    lan_servers: (( properties.consul.agent.servers.lan ))

# The keys below should not be included in the final stub
name: (( merge ))
properties:
  cc:
    srv_api_uri: (( merge ))
  consul:
    agent:
      log_level: (( merge ))
      servers:
        lan: (( merge ))
  ssl:
    skip_cert_verify: (( merge ))
  app_domains: (( merge ))

