config_from_diego:
  bbs:
    api_location: (( properties.diego.auctioneer.bbs.api_location ))
    ca_cert: (( properties.diego.auctioneer.bbs.ca_cert ))
    client_cert: (( properties.diego.auctioneer.bbs.client_cert ))
    client_key: (( properties.diego.auctioneer.bbs.client_key ))
    require_ssl: (( properties.diego.auctioneer.bbs.require_ssl ))
    client_session_cache_size: (( properties.diego.auctioneer.bbs.client_session_cache_size ))
    max_idle_conns_per_host: (( properties.diego.auctioneer.bbs.max_idle_conns_per_host ))

# The keys below should not be included in the final stub
properties:
  diego:
    auctioneer:
      bbs:
        api_location: (( merge ))
        ca_cert: (( merge ))
        client_cert: (( merge ))
        client_key: (( merge ))
        require_ssl: (( merge ))
        client_session_cache_size: (( merge ))
        max_idle_conns_per_host: (( merge ))
