name: (( config_from_cf.cf_deployment_name "-diego-perf" ))
director_uuid: (( config_from_cf.cf_director_uuid ))

releases:
  - name: diego-perf-release
    version: latest
  - name: cf
    version: latest

compilation:
  workers: 6
  network: cedar
  reuse_compilation_vms: true
  cloud_properties: (( iaas_settings.compilation_cloud_properties ))

update:
  canaries: 1
  canary_watch_time: 5000-120000
  update_watch_time: 5000-120000
  max_in_flight: 1
  serial: false

networks:
  - name: cedar
    type: manual
    subnets: (( iaas_settings.subnet_configs.cedar.subnets ))

resource_pools:
  - name: cedar
    network: cedar
    stemcell: (( iaas_settings.stemcell ))
    cloud_properties: (( iaas_settings.resource_pool_cloud_properties.cedar.cloud_properties ))

jobs:
  - name: cedar
    templates:
      - name: arborist
        release: diego-perf-release
      - name: cedar
        release: diego-perf-release
      - name: fezzik
        release: diego-perf-release
    instances: (( instance_count_overrides.cedar.instances || 1 ))
    persistent_disk: 4096
    resource_pool: cedar
    networks:
      - name: cedar

properties:
  cedar:
    api: (( config_from_cf.cc.api_uri ))
    domain: (( config_from_cf.first_app_domain ))
    admin_user: (( property_overrides.cc_admin_user || "" )) # unfortunate hack because we can't get it from cf manifest
    admin_password: (( property_overrides.cc_admin_password || "" ))  # unfortunate hack because we can't get it from cf manifest
    skip_ssl_validation: (( config_from_cf.skip_ssl_validation ))
    batches: (( property_overrides.cedar.batches || nil ))

  fezzik:
    bbs:
      api_location: (( "bbs.service.cf.internal:8889" ))
      ca_cert: (( config_from_diego.bbs.ca_cert ))
      client_cert: (( config_from_diego.bbs.client_cert ))
      client_key: (( config_from_diego.bbs.client_key ))
      require_ssl: (( config_from_diego.bbs.require_ssl || nil ))
  performance_tests:
    num_cells: (( property_overrides.num_cells || nil ))

# The keys below should not be included in the final stub
config_from_cf: (( merge ))
config_from_diego: (( merge ))
property_overrides: (( merge ))
iaas_settings: (( merge ))
instance_count_overrides: (( merge ))
