iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  subnet_configs:
    - name: perf
      type: manual
      subnets:
      - cloud_properties: {}
        range: 10.244.17.0/30
        reserved:
        - 10.244.17.1
        static:
        - 10.244.17.2
      - cloud_properties: {}
        range: 10.244.17.4/30
        reserved:
        - 10.244.17.5
        static: []
      - cloud_properties: {}
        range: 10.244.17.8/30
        reserved:
        - 10.244.17.9
        static: []
      - cloud_properties: {}
        range: 10.244.17.12/30
        reserved:
        - 10.244.17.13
        static: []
      - cloud_properties: {}
        range: 10.244.17.16/30
        reserved:
        - 10.244.17.17
        static: []
      - cloud_properties: {}
        range: 10.244.17.20/30
        reserved:
        - 10.244.17.21
        static: []
      - cloud_properties: {}
        range: 10.244.17.24/30
        reserved:
        - 10.244.17.25
        static: []
      - cloud_properties: {}
        range: 10.244.17.28/30
        reserved:
        - 10.244.17.29
        static: []
      - cloud_properties: {}
        range: 10.244.17.32/30
        reserved:
        - 10.244.17.33
        static: []
      - cloud_properties: {}
        range: 10.244.17.36/30
        reserved:
        - 10.244.17.37
        static: []
      - cloud_properties: {}
        range: 10.244.17.40/30
        reserved:
        - 10.244.17.41
        static: []
      - cloud_properties: {}
        range: 10.244.17.44/30
        reserved:
        - 10.244.17.45
        static:
        - 10.244.17.46
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: cedar
      cloud_properties: {}
